Rename csi shares amount metric
openshift/csi-driver-shared-resource-operator pull request #35
Opened 2021-11-29 12:45 UTC by alicerum

According to best practices, gauge metrics should not contain `_total` suffix in its name.

2021-11-29 13:49 UTC, alicerum commented
/assign @gabemontero

2021-11-29 18:16 UTC, gabemontero requested changes
per the exchange in the driver metric PR, should not these metrics end in `_total`

2021-11-30 13:24 UTC, gabemontero commented
/approve

@alicerum - address my comment https://github.com/openshift/csi-driver-shared-resource-operator/pull/35#pullrequestreview-818151381 and then follow the pattern I did in https://github.com/openshift/csi-driver-shared-resource/pull/78#issuecomment-982619120 to get the appropriate non feature freeze labels applied to this PR so it can merge without a BZ

2021-12-02 18:57 UTC, alicerum commented
/assign @jitendar-singh 
Assigning for the qe approve label

/assign @rolfedh
For docs approve label

2021-12-06 18:14 UTC, rolfedh commented
/label docs-approve

2021-12-06 18:19 UTC, rolfedh commented
/label docs-approved

2021-12-07 13:16 UTC, prietyc123 commented
/label qe-approved

2021-12-09 15:13 UTC, gabemontero commented
/label px-approved
/approve
/lgtm

2021-12-09 16:28 UTC, merged