add cheap/meets min way of handling crd/cm deletes
openshift/csi-driver-shared-resource-operator pull request #36
Opened 2021-11-29 19:29 UTC by gabemontero

Fixes #23 

/assign @coreydaley

2021-11-29 19:41 UTC, coreydaley requested changes

2021-11-29 19:41 UTC, coreydaley commented on pkg/operator/starter.go
> +	_, err = kubeClient.CoreV1().ConfigMaps(defaultNamespace).Get(ctx, "csi-driver-shared-resource-config", metav1.GetOptions{})
```suggestion
	_, err = kubeClient.CoreV1().ConfigMaps(defaultNamespace).Get(ctx, configMap.Name, metav1.GetOptions{})
```

2021-11-29 19:41 UTC, coreydaley commented on pkg/operator/starter.go
> +			return fmt.Errorf("error occurred creating 'csi-driver-shared-resource-config' ConfigMap: %s", err)
```suggestion
			return fmt.Errorf("error occurred creating %q ConfigMap: %s", configMap.Name, err)
```

2021-11-29 19:41 UTC, coreydaley commented on pkg/operator/starter.go
> +		return fmt.Errorf("unexpected error determining if 'csi-driver-shared-resource-config' exists: %s", err)
```suggestion
		return fmt.Errorf("unexpected error determining if %q exists: %s", configMap.Name, err)
```

2021-11-29 20:10 UTC, gabemontero commented
updated @coreydaley thanks

2021-11-30 13:27 UTC, gabemontero commented
/assign @prietyc123 

for qe approved label

/assign @rolfedh 

for docs approved label

/assign @adambkaplan 

for px approved label

2021-11-30 15:10 UTC, coreydaley commented
/lgtm

2021-11-30 19:41 UTC, rolfedh commented
@gabemontero Do these changes have any doc impacts?

2021-11-30 20:51 UTC, gabemontero commented
> @gabemontero Do these changes have any doc impacts?

no doc impacts for this one @rolfedh .... this change is just reliability fixes

2021-12-01 11:35 UTC, rolfedh approved these changes

2021-12-01 13:16 UTC, gabemontero commented
thanks @rolfedh, but your using github pr approve is not sufficient for us.  You need post a comment with

/label docs-approved

2021-12-01 13:17 UTC, gabemontero commented
how about that ... I didn't know I had that power in this repo @rolfedh :-)

in the future, if you could use that prow command, that would be great

2021-12-01 13:17 UTC, gabemontero commented
/label px-approved

2021-12-01 13:22 UTC, rolfedh commented
/label docs-approved

2021-12-01 13:53 UTC, gabemontero commented
Priti is out sick

/assign @jitendar-singh 

for qe approved

2021-12-01 14:25 UTC, jitendar-singh commented
/label qe-approved

2021-12-02 20:35 UTC, gabemontero commented
> /label qe-approved

@adambkaplan - looks like @jitendar-singh does not have the power to apply qe-approved for this repo

He was able to do it for csi-driver-shared-resource-operator PRs.

However, in comparing https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/csi-driver-shared-resource-operator/_pluginconfig.yaml and https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/csi-driver-shared-resource/_pluginconfig.yaml I don't see the difference that explains how to get him that power.

Can you follow up as part of what you did to enable no-FF for this repo in the first place?

thanks

2021-12-02 20:37 UTC, adambkaplan commented
Added this manually (looks like I do have that power). Will look into qe-approvers in openshift/release.

2021-12-02 20:38 UTC, merged

2021-12-02 20:46 UTC, adambkaplan commented
Looks like there is no special permission for qe-approved. This isn't the case for backport-approved and cherrypick-approved.

My guess is that the prow bot didn't receive the event for one reason or another. Our webhook with GitHub is known to flake on occasion.

2021-12-02 20:58 UTC, gabemontero commented
> Looks like there is no special permission for qe-approved. This isn't the case for backport-approved and cherrypick-approved.
> 
> My guess is that the prow bot didn't receive the event for one reason or another. Our webhook with GitHub is known to flake on occasion.

cool thanks @adambkaplan