BUILD-405: Install shared resource csi driver webhook alongside the s…
openshift/csi-driver-shared-resource-operator pull request #45
Opened 2022-05-10 05:46 UTC by jkhelil

…hared resource csi driver

2022-05-11 08:30 UTC, jkhelil commented
/test e2e-aws-techpreview

2022-05-15 09:11 UTC, jkhelil commented
/test e2e-aws-techpreview

2022-05-16 13:35 UTC, jkhelil commented
/test e2e-aws-csi-driver

2022-05-16 19:25 UTC, jkhelil commented
/retest

2022-05-17 07:32 UTC, jkhelil commented
/test e2e-aws-csi-driver

2022-05-17 07:33 UTC, jkhelil commented
/test e2e-aws-techpreview

2022-05-18 14:31 UTC, jkhelil commented
/test e2e-aws-techpreview

2022-05-19 13:41 UTC, jkhelil commented
/retest

2022-05-20 05:49 UTC, jkhelil commented
/retest

2022-05-20 14:16 UTC, coreydaley commented
/retest

2022-05-20 14:17 UTC, coreydaley commented
/assign coreydaley

2022-05-20 14:27 UTC, coreydaley requested changes

2022-05-20 14:27 UTC, coreydaley commented on pkg/operator/starter.go
> +	webhookdeployment "github.com/openshift/csi-driver-shared-resource-operator/pkg/deploymentcontroller"
```suggestion
	"github.com/openshift/csi-driver-shared-resource-operator/pkg/deploymentcontroller"
```

2022-05-20 14:27 UTC, coreydaley commented on pkg/operator/starter.go
> +	webhookDeploymentController := webhookdeployment.NewWebHookDeploymentController(
```suggestion
	webhookDeploymentController := deploymentcontroller.NewWebHookDeploymentController(
```

2022-05-20 14:27 UTC, coreydaley commented on assets/assets.go
> +}
```suggestion
// MustAsset reads and returns the content of the file at path or panics
// if something went wrong.
func MustAsset(path string) []byte {
	data, err := f.ReadFile(path)
	if err != nil {
		panic(err)
	}

	return data
}
```

2022-05-23 06:55 UTC, jkhelil commented
/test e2e-aws-techpreview

2022-05-23 14:26 UTC, coreydaley commented
/retest

2022-05-25 00:31 UTC, coreydaley commented
/retest

2022-05-25 11:58 UTC, jkhelil commented
/retest

2022-05-25 12:03 UTC, jkhelil commented on pkg/operator/starter.go
> +	webhookDeploymentController := webhookdeployment.NewWebHookDeploymentController(
fixed

2022-05-25 12:03 UTC, jkhelil commented on pkg/operator/starter.go
> +	webhookdeployment "github.com/openshift/csi-driver-shared-resource-operator/pkg/deploymentcontroller"
fixed

2022-05-25 12:28 UTC, coreydaley commented on hack/deploy.sh
> +operatorImage=${OPERATOR_IMAGE:-quay.io/jkhelil/origin-csi-driver-shared-resource-operator:latest}
Does this need to be set back to `openshift`?

2022-05-25 15:13 UTC, coreydaley commented on hack/deploy.sh
> +operatorImage=${OPERATOR_IMAGE:-quay.io/jkhelil/origin-csi-driver-shared-resource-operator:latest}
This is still not `openshift`?

2022-05-25 16:52 UTC, jkhelil commented
we should fix 
```
1 pods found in best-effort QoS:
openshift-cluster-csi-drivers/shared-resource-csi-driver-webhook-5b5bf5746f-xthwv is running in best-effort QoS

```

2022-05-25 18:39 UTC, coreydaley commented
/approve
/label docs-approved
/label qe-approved
/label px-approved

2022-05-25 18:44 UTC, merged